#!/bin/bash
### BEGIN INIT INFO
# Provides:          EzFrontendUI
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: This is the EzFrontendUI
# Description:       This is the EzFrontendUI
### END INIT INFO

# Source function library.
. /etc/init.d/functions

servicename=EzFrontendUI
RETVAL=0
LOCKFILE=/var/lock/subsys/${servicename}

EFE_PREFIX=/opt/ezfrontend-ui
PIDFILE="${EFE_PREFIX}/pidfile"
EFE_USER=ezfrontendui

EFE_START="${EFE_PREFIX}/ezfrontendui/ezfrontendui"
EFE_STOP="${EFE_PREFIX}/stop"

start() {
	echo -n "Starting ${servicename}: "
	chown -R ${EFE_USER}:${EFE_USER} "${EFE_PREFIX}"
	export EZBAKE_ENCRYPTION_SECRET=$(runuser ${EFE_USER} -l sh -c 'echo ${EZBAKE_ENCRYPTION_SECRET}')
	daemon --user ${EFE_USER} --pidfile ${PIDFILE} "cd ${EFE_PREFIX} && ($EFE_START &>/dev/null & echo \$! > ${PIDFILE})"
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch $LOCKFILE

	echo
	return $RETVAL
}	

stop() {
	echo -n "Shutting down ${servicename}: "
        kill $(<${PIDFILE}) && success || failure
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $LOCKFILE
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $PIDFILE
	RETVAL=$?
	echo
	return $RETVAL
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	echo -n "Status of ${servicename}: "
	if [ -f "$PIDFILE" ]; then
		echo "running"
		RETVAL=0
	elif [ -f "$LOCKFILE" ]; then
		echo -n "dead"
		RETVAL=2
	else
		echo -n "dead"
		RETVAL=3
	fi
	echo
	;;
    restart)
	stop
	sleep 1
	start
	;;
    reload)
	#<cause the service configuration to be reread, either with
	#kill -HUP or by restarting the daemons, in a manner similar
	#to restart above>
	;;
    *)
	echo "Usage: ${servicename} {start|stop|status|reload|restart}"
	exit 1
	;;
esac
exit $RETVAL


